

def raiseError(message):
    raise Exception(message)
